export const SLEEP_TIME_AFTER_AUTO_REDEEM_CHECK = 30 * 60 * 1000; // 30 minutes
export const SLEEP_TIME_AFTER_AUTO_REDEEM_CHECK_FAILED = 10 * 60 * 1000; // 10 minutes
export const SLEEP_TIME_AFTER_CLAIM_MULTIPLE_REDEEMS = 10000; // 10 seconds
export const BATCH_SIZE_FOR_CLAIM_MULTIPLE_REDEEMS = 25;
